#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'pss==1.40','console_scripts','pss'
__requires__ = 'pss==1.40'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pss==1.40', 'console_scripts', 'pss')()
    )
